# -*- coding: utf-8 -*-
"""music_genre_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11P1q7iZ50mblVWfGJ5Vg7kfvwf11bhat
"""

!pip install librosa



# ------------------------------
# IMPORTS
# ------------------------------

import numpy as np
import os
import librosa
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# ------------------------------
# REPRODUCIBILIDAD
# ------------------------------

np.random.seed(42)
tf.random.set_seed(42)


# dataset/
#    rock/
#    pop/
#    jazz/
#    classical/
#    hiphop/
#    electronic/
!wget https://web.archive.org/web/20220328223413/ftp://opihi.cs.uvic.ca/sound/genres.tar.gz
!tar -xzf genres.tar.gz

DATASET_PATH = "genres"
SAMPLE_RATE = 22050
DURATION = 30

CHUNK_DURATION = 3  # clave
SAMPLES_PER_CHUNK = SAMPLE_RATE * CHUNK_DURATION

N_MELS = 128
HOP_LENGTH = 512

# ------------------------------
# GPU
# ------------------------------

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    tf.config.experimental.set_memory_growth(gpus[0], True)
    print("GPU activa")
else:
    print("CPU activa")

# ------------------------------
# FUNCIÓN: MEL SPECTROGRAM
# ------------------------------

def extract_mel(signal, sr):
    mel = librosa.feature.melspectrogram(
        y=signal,
        sr=sr,
        n_mels=N_MELS,
        hop_length=HOP_LENGTH
    )

    mel_db = librosa.power_to_db(mel)

    return mel_db.astype(np.float32)

# ------------------------------
# FUNCIÓN: DIVIDIR AUDIO EN CHUNKS
# ------------------------------
def split_chunks(signal):
    chunks = []

    for i in range(0, len(signal), SAMPLES_PER_CHUNK):
        chunk = signal[i:i + SAMPLES_PER_CHUNK]

        if len(chunk) == SAMPLES_PER_CHUNK:
            chunks.append(chunk)

    return chunks

# ------------------------------
# FUNCIÓN: CARGA DEL DATASET
# ------------------------------
def load_dataset(dataset_path):
    X, y = [], []

    for genre in sorted(os.listdir(dataset_path)):
        genre_path = os.path.join(dataset_path, genre)

        if not os.path.isdir(genre_path):
            continue

        print("Procesando:", genre)

        for file in os.listdir(genre_path):
            file_path = os.path.join(genre_path, file)

            try:
                signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)

                chunks = split_chunks(signal)

                for chunk in chunks:
                    mel = extract_mel(chunk, sr)

                    # normalizar por muestra
                    mel = (mel - np.mean(mel)) / (np.std(mel) + 1e-6)

                    X.append(mel)
                    y.append(genre)

            except Exception as e:
                print("Error:", file_path, e)

    return np.array(X), np.array(y)

# ------------------------------
# CARGAR DATOS
# ------------------------------
X, y = load_dataset(DATASET_PATH)

# reshape para CNN
X = X[..., np.newaxis]  # (samples, mel, time, 1)

# ------------------------------
# ENCODING DE ETIQUETAS
# ------------------------------
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_cat = to_categorical(y_encoded)

# ------------------------------
# TRAIN / TEST SPLIT
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y_cat, test_size=0.2, stratify=y_encoded, random_state=42
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input

# ------------------------------
# MODELO CNN2D
# ------------------------------

model = Sequential([
    Input(shape=X.shape[1:]),

    Conv2D(32, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Conv2D(128, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D((2,2)),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.4),

    Dense(y_train.shape[1], activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=['accuracy']
)

model.summary()

# ------------------------------
# CALLBACKS
# ------------------------------
callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(patience=5)
]

# ------------------------------
# ENTRENAMIENTO
# ------------------------------
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=50,
    batch_size=32,
    callbacks=callbacks
)

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# ------------------------------
# MATRIZ DE CONFUCION
# ------------------------------
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=le.classes_,
            yticklabels=le.classes_)

plt.title("Matriz de Confusión")
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.xticks(rotation=45)
plt.yticks(rotation=45)
plt.tight_layout()
plt.show()

print(classification_report(y_true, y_pred, target_names=le.classes_))

# ------------------------------
# EVALUACIÓN
# ------------------------------
loss, acc = model.evaluate(X_test, y_test)
print(f"\nAccuracy test: {acc*100:.2f}%")

# ------------------------------
# PREDICCIÓN CON VOTING
# ------------------------------
def predict_genre(file_path, model, label_encoder):
    signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)

    chunks = split_chunks(signal)

    preds = []

    for chunk in chunks:
        mel = extract_mel(chunk, sr)
        mel = (mel - np.mean(mel)) / (np.std(mel) + 1e-6)

        mel = mel[np.newaxis, ..., np.newaxis]

        pred = model.predict(mel, verbose=0)
        preds.append(pred[0])

    preds = np.array(preds)

    # promedio de predicciones
    final_pred = np.mean(preds, axis=0)

    idx = np.argmax(final_pred)

    # Graficar
    plt.figure(figsize=(10, 5))
    plt.bar(label_encoder.classes_, final_pred, color='skyblue')
    plt.title("Distribución de Probabilidades por Género")
    plt.ylabel("Probabilidad")
    plt.xticks(rotation=45)
    plt.show()

    print("\nResultado final:")
    for i, p in enumerate(final_pred):
        print(f"{label_encoder.classes_[i]}: {p*100:.2f}%")

    return label_encoder.classes_[idx]

# ------------------------------
# EJEMPLO DE USO
# ------------------------------
predict_genre("test-rock.wav", model, le)

# ------------------------------
# GUARDAR MODELO
# ------------------------------
model.save("music_genre_classifier.keras")
print("Modelo guardado correctamente")