# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6QMK6Rulj21zwAfBKvtdamkX0DqHQm4
"""

!pip install librosa

import numpy as np
import pandas as pd
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# dataset/
#    rock/
#    pop/
#    jazz/
#    classical/
#    hiphop/
#    electronic/
!wget https://web.archive.org/web/20220328223413/ftp://opihi.cs.uvic.ca/sound/genres.tar.gz
!tar -xzf genres.tar.gz
DATASET_PATH = "/content/genres"
print("--->",DATASET_PATH)
print("--->",os.listdir(DATASET_PATH))

SAMPLE_RATE = 22050
DURATION = 30  # segundos
SAMPLES_PER_TRACK = SAMPLE_RATE * DURATION

def extract_features(dataset_path, n_mfcc=13, duration=30):
    X = []
    y = []

    SAMPLES_PER_TRACK = SAMPLE_RATE * duration
    VALID_EXTENSIONS = (".wav", ".au", ".mp3")

    for genre in os.listdir(dataset_path):
        genre_path = os.path.join(dataset_path, genre)

        if not os.path.isdir(genre_path):
            continue

        print(f"Procesando: {genre}")

        for file in os.listdir(genre_path):
            file_path = os.path.join(genre_path, file)

            if not file.lower().endswith(VALID_EXTENSIONS):
                continue

            try:
                signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)

                # 🔥 Forzar misma duración
                if len(signal) >= SAMPLES_PER_TRACK:
                    signal = signal[:SAMPLES_PER_TRACK]
                else:
                    padding = SAMPLES_PER_TRACK - len(signal)
                    signal = np.pad(signal, (0, padding))

                mfcc = librosa.feature.mfcc(
                    y=signal,
                    sr=sr,
                    n_mfcc=n_mfcc
                )
                mfcc = mfcc.T

                X.append(mfcc)
                y.append(genre)

            except Exception as e:
                print(f"Error en {file_path}: {e}")

    return np.array(X), np.array(y)

X, y = extract_features(DATASET_PATH)

print(f"Total muestras: {len(X)}")

from tensorflow.keras.preprocessing.sequence import pad_sequences

MAX_LEN = 1300  # ajustable

X_padded = pad_sequences(X, maxlen=MAX_LEN, padding='post', truncating='post')

le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_categorical = to_categorical(y_encoded)

X_train, X_test, y_train, y_test = train_test_split(
    X_padded, y_categorical, test_size=0.2, random_state=42
)

model = Sequential()

model.add(LSTM(128, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu'))
model.add(Dense(y_categorical.shape[1], activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=150,
    batch_size=32
)

loss, acc = model.evaluate(X_test, y_test)
print(f"Accuracy: {acc:.2f}")

def predict(file_path, model, label_encoder):
    signal, sr = librosa.load(file_path, sr=SAMPLE_RATE)
    mfcc = librosa.feature.mfcc(
        y=signal,
        sr=sr,
        n_mfcc=13
    )
    mfcc = mfcc.T

    mfcc = pad_sequences([mfcc], maxlen=MAX_LEN, padding='post', truncating='post')

    prediction = model.predict(mfcc)
    predicted_label = label_encoder.inverse_transform([np.argmax(prediction)])

    return predicted_label[0]

test_file = "/content/test.wav"
print(predict(test_file, model, le))

model.save("music_genre_classifier.h5")